import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ContextProvider from "@/providers/ContextProvider";
import { Toaster } from "react-hot-toast";
import QueryProvider from "@/providers/QueryProvider";
import ModalProvider from "@/providers/ModalProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.className} h-full antialiased`}>
      <ContextProvider>
        <body className="flex min-h-full flex-col">
          <Toaster />
          <QueryProvider>
            <ModalProvider>
              <main>{children}</main>
            </ModalProvider>
          </QueryProvider>
        </body>
      </ContextProvider>
    </html>
  );
}
